config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'recipes#index'

  resources :users do
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      member do
      patch 'toggle'
      end
      resources :recipe_foods, only: [:show, :new, :create, :destroy]
    end
    get 'shopping_list', to: 'users#shopping_list', as: 'shopping_list' do
  end
end

resources :foods, only: [:index, :show, :new, :create, :destroy]
resources :recipes, only: [:index, :show, :new, :create, :destroy]

resources :public_recipes, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user

    # return unless user

    # Abilities for all users
    can %i[read create], Food
    can %i[read create], Recipe
    can %i[read create], RecipeFood

    # Abilities for the user's own records
    can %i[update destroy], Food, user_id: user.id
    can %i[update destroy], Recipe, user_id: user.id
    can %i[update destroy], RecipeFood, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  has_many :food_recipes, foreign_key: 'food_id'

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods, foreign_key: 'recipe_id'
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 500 }
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true

  def total_price
    # Total price for the recipe
    recipe_foods.sum { |rf| rf.food.price * rf.quantity }
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }

  has_many :recipes, foreign_key: 'user_id'
  has_many :foods, foreign_key: 'user_id'

  def shopping_list
    # Get all recipe foods for current user's recipes
    recipe_foods = RecipeFood.joins(:recipe).where(recipes: { user_id: id })

    # Group recipe foods by their associated food items and calculate the total quantity required for each food item
    required_foods = recipe_foods.group(:food_id).sum(:quantity)

    # Hash to store shopping list items
    shopping_list = {}

    # Initialize items and values variables
    total_items = 0
    total_value = 0

    # Compare the total quantity of each food item required with the quantity of that food item currently in stock
    required_foods.each do |food_id, quantity|
      food = Food.find(food_id)
      available_quantity = food.quantity || 0
      quantity_required = [0, quantity - available_quantity].max

      next unless quantity_required.positive?

      # Calculate the total price for the required quantity
      total_price = quantity_required * food.price
      shopping_list[food] = { quantity: quantity_required, total_price: }

      # Increment total items and total value
      total_items += quantity_required
      total_value += total_price
    end

    { shopping_list:, total_items:, total_value: }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    if @food.save
      flash[:success] = 'Food was successfully created'
      redirect_to foods_path
    else
      flash[:alert] = 'Food was not created'
      render 'new'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:danger] = 'Food was successfully deleted'
    redirect_to foods_path
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true)
      .order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @foods = current_user.foods.pluck(:name, :id)
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @existing_food = @recipe.foods.pluck(:id)
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe = Recipe.find(params[:recipe_food][:recipe_id])
    @existing_food = @recipe.foods.pluck(:id)

    if @existing_food.include?(@recipe_food.food_id)
      flash[:alert] = 'Ingredient already exists in your recipe'
      redirect_to new_user_recipe_recipe_food_path(user_id: current_user.id, recipe_id: @recipe.id)
      return
    end

    if @recipe_food.save
      flash[:success] = 'Ingredient successfully added to your recipe'
      redirect_to recipe_path(user_id: current_user.id, id: @recipe_food.recipe_id)
    else
      flash[:alert] = 'Failed to add ingredient to your recipe'
      render 'new'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(user_id: current_user.id, id: @recipe_food.recipe_id)
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @user = current_user
    @food = Food.all
    @recipe = Recipe.find(params[:id])
    @recipe_food = RecipeFood.where(recipe_id: @recipe.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:notice] = 'Recipe was added to the table successfully .'
      redirect_to recipes_path
    else
      flash[:alert] = 'Recipe was not added to the table.'
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.recipe_foods.destroy_all
    @recipe.destroy
    flash[:notice] = 'Recipe was successfully deleted.'
    redirect_to recipes_path
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to recipe_path
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def shopping_list
    @user = current_user
    shopping_list_data = @user.shopping_list

    @shopping_list = shopping_list_data[:shopping_list]
    @total_price = shopping_list_data[:total_price]
    @total_value = shopping_list_data[:total_value]
  end

  private

  def user_params
    params.require(user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="food-page">
  <div class="add-food-btn">
    <%= button_to "Add Food", new_food_path, method: :get, class: "btn" %>
  </div>

  <% if @foods.empty? %>
    <p>No food available for this user.</p>
  <% else %>
    <table class="food-table">
      <thead>
        <tr>
          <th class="row-left-style">Food</th>
          <th>Measurement Unit</th>
          <th>Unit Price</th>
          <th class="row-right-style">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td>
              <%= number_to_currency(food.price, unit: '$', precision: 2) %>
            </td>
            <td>
              <% if RecipeFood.exists?(food_id: food.id) %>
                <span>Is part of a recipe</span>
              <% else %>
                <%= link_to "Delete", food_path(food), data: { turbo_method: :delete }, class: "action-btn" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/foods/new.html.erb
<div class="new-food">
  <h1>Add a new food</h1>
  <div class="add-food-section">
    <%= form_with(model: @food, url: foods_path(@user), class: 'add-food-form') do |form| %>
      <div class="food-field">
        <%= form.label :name %>
        <%= form.text_field :name, required: true %>
      </div>

      <div class="food-field">
        <%= form.label :measurement_unit %>
        <%= form.select :measurement_unit, options_for_select(['mg', 'gr', 'Kg', 'oz', 'lt', 'u']), { include_blank: 'Choose a measurement unit'}, class: 'form-control' %>
      </div>

      <div class="food-field">
        <%= form.label :price %>
        <%= form.number_field :price, required: true, step: '0.01', min: '0.01', value: sprintf('%.2f', @food.price || 0.00) %>
      </div>

      <div class="food-field">
        <%= form.label :quantity %>
        <%= form.number_field :quantity, required: true, step: '0.01' %>
      </div>

      <div class="food-field">
        <%= form.submit "Add Food", class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <header>
        <nav class="navbar">
          <div class="logo-area">
            <h1 class="logo"><%= link_to "Recipes&Foods", root_path %></h1>
            <p>Hi, <%= current_user.name %>!</p>
          </div>
          <ul class="navbar-links">
            <li><%= link_to "Recipes", root_path %></li>
            <li><%= link_to "Public Recipes", public_recipes_path %></li>
            <li><%= link_to "Foods", foods_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete } %></li>
          </ul>
        </nav>
      </header>
      <% else %>
        <header>
          <nav class="navbar">
            <h1 class="logo"><%= link_to "Recipes&Foods", root_path %></h1>
            <ul class="navbar-links">
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            </ul>
          </nav>
        </header>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="public_recipes_page">
  <h1>Public Recipes</h1>
  <div class="public_recipes">
    <% @public_recipes.each do |recipe| %>
      <div class="recipe-card">
        <div class="left-recipe-col">
          <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
          <p>By: <%= recipe.user.name %></p>
        </div>
        <div class="right-recipe-col">
          <p>Total Ingredients: <%= recipe.recipe_foods.map(&:food_id).uniq.count %></p>
          <p>Total Price: $<%= number_with_precision(recipe.total_price, precision: 2) %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="new-food">
  <h1>Add Ingredient To Recipe</h1>
  <%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path(user_id: @recipe.user.id, recipe_id: @recipe.id), class: 'add-food-form', local: true do |f| %>
    <div class="food-field">
      <%= f.label :name %>
      <%= f.select :food_id, options_for_select(@foods), { include_blank: 'Choose a food'}, class: 'form-control' %>
    </div>

    <div class="food-field">
      <%= f.label :quantity %>
      <%= f.number_field :quantity, required: true, step: '0.01', placeholder: "Quantity" %>
    </div>

    <% if @existing_food.include?(@recipe_food.food_id) %>
      <p class="alert alert-warning">This ingredient is already part of the recipe.</p>
    <% end %>

    <%= f.hidden_field :recipe_id, value: @recipe.id %>

    <div class="actions">
      <%= f.submit "Add Ingredient", class: "btn" %>
    </div>
  <% end %>

  <div>
    <% flash.each do |key, message| %>
      <div class="flash-<%= key %>">
        <%= message %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="recipes_page">
  <h1 class="recipe-page">Recipe List</h1>
  <div class="add-recipe-btn">
    <%= button_to "Add Recipe", new_recipe_path, method: :get, class: "btn" %>
  </div>

  <div class="flex recipes-container">
    <% @recipes.each do |recipe| %>
      <div class="flex recipe-card">
        <div class="left-recipe-col">
          <h2><%= link_to recipe.name, recipe_path(recipe) %></h2>
          
            <%= button_to "Remove", recipe_path(recipe), method: :delete, class: "btn del-btn" %>
          
        </div>
        <div class="right-recipe-col">
          <p><%= recipe.description %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="new-recipe">
<h1>Add new recipe</h1>
<div class="add-recipe-section">
<%= form_with( model: @recipe, url: recipes_path(@user), class: "add-recipe-form") do |f| %>
  <div class="recipe-field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="recipe-field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="recipe-field">
    <%= f.label :preparation_time %>
    <%= f.text_field :preparation_time %>
  </div>

  <div class="recipe-field">
    <%= f.label :cooking_time %>
    <%= f.text_field :cooking_time %>
  </div>
  <div>
    <%= f.label :public %><br>
    <%= f.select :public, options_for_select(['true', 'false']) %>
  </div>

   <div class="recipe-field">
  <%= f.submit "Add Recipe", class: "btn"%>
<% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="food-page">
  <h1>Recipes Details</h1>
  <div class="recipes-section">
    <h1><%= @recipe.name %></h1>
    <div class="recipe-info">
      <div class="recipe-info-public">
        <p>Preparation time: <%= @recipe.preparation_time %> hour(s)</p>
        <div class="public-selector">
          <% if current_user == @recipe.user %>
              <%= button_to "Public: ", toggle_user_recipe_path(user_id: current_user.id, id: @recipe.id), method: :patch, class: "btn toggle-public-btn" %>
              <h4><%= @recipe.public? ? 'Yes' : 'No' %></h4>
          <% end %>
        </div>  
      </div>
      <p>Cooking time: <%= @recipe.cooking_time %> hour(s)</p>
      <p>Decription: <%= @recipe.description %></p>
    </div>
    
    <div class="recipe-btn">
      <% if current_user == @recipe.user %>
        <%= button_to "Generate Shopping List", user_shopping_list_path(user_id: @recipe.user.id, recipe_id: @recipe.id), method: :get, class: "btn" %>
        <%= button_to "Add Ingredient", new_user_recipe_recipe_food_path(user_id: @recipe.user.id, recipe_id: @recipe.id), method: :get, class: "btn" %>
      <% end %>
    </div>
    
    <hr>
    
    <div class="food-page">
      <% if @recipe_food.blank? %>
        <p>No food ingredients available for this recipe.</p>
      <% else %>
        <table class="food-table">
          <thead>
            <tr>
              <th class="row-left-style">Food</th>
              <th>Quantity</th>
              <th>Value</th>
              <th class="row-right-style">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @recipe_food.each do |recipe_food| %>
              <tr>
                <td><%= recipe_food.food.name %></td>
                <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
                <td>
                  <%= '$' %>
                  <% value = recipe_food.quantity * recipe_food.food.price %>
                  <%= number_with_precision(value, precision:2) %>
                </td>
                <td>
                  <%= link_to "Remove", user_recipe_recipe_food_path(user_id: @recipe.user.id, recipe_id: @recipe.id, id: recipe_food.id), data: { turbo_method: :delete }, class: "action-btn" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-section">
  <h1>List of Users</h1>
  <% @users.each do |user| %>
    <p><%= user.name %></p>
  <% end %>
</div>

app/views/users/shopping_list.html.erb
<div class="shopping_list_page food-page">
  <h1>Shopping List</h1>
  <div class="shopping_list">
    <% if @shopping_list[:shopping_list].blank? %>
      <div class="shopping-list-summary">
        <p>Amount of ingredients to buy: <%= @shopping_list.keys.size %></p>
        <p>Total value of food needed: <%= number_to_currency(@total_value) %></p>
      </div>
      <div class="food-table shopping-data">
        <table class="shopping-table">
          <thead>
            <tr>
              <th class="shopping-table-width row-left-style">Food</th>
              <th class="shopping-table-width">Quantity</th>
              <th class="shopping-table-width row-right-style">Price</th>
            </tr>
          </thead>
          <tbody>
            <% @shopping_list.each do |food, info| %>
              <tr>
                <td class="shopping-table-width"><%= food.name %></td>
                <td class="shopping-table-width"><%= info[:quantity] %> <%= food.measurement_unit %></td>
                <td class="shopping-table-width"><%= '$' %> <%= number_with_precision(info[:total_price], precision:2) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p>No ingredients to buy.</p>
    <% end %>
  </div>
</div>